config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root 'home#index'

  get '/profiles' => 'profile#index'
  get '/profile/edit' => 'profiles#edit'
  post '/profile/update' => 'profiles#update'
  get '/profile/move/:move' => 'profiles#show'
  get '/profile' => 'profiles#show'
  get '/profile/:username' => 'profiles#show'

  get '/events/:id/attend' => 'attendances#create'
  get '/events/:id/unattend' => 'attendances#destroy'

  get '/users' => 'users#index'
  
  resources :events
  resources :groups

  post '/signup' => 'users#create'
  post '/login' => 'session#create'
  delete '/log_out' => 'session#destroy'

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
	belongs_to :user
	belongs_to :event
end

app/models/event.rb
class Event < ActiveRecord::Base
	validates :title,
				 uniqueness: true,
				 presence: {message: "must be filled in"}

	validates :address_1,
				 presence: true

	validates :city,
				 presence: true

	validates :state,
				 presence: true

	validates :date,
				 presence: true

	validates :creator_id,
				 presence: true
				 
	has_many :attendances			 
	has_many :users, through: :attendances
end

app/models/follow.rb
class Follow < ActiveRecord::Base
	belongs_to :followee, :class_name => :User
	belongs_to :follower, :class_name => :User
end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :users, through: :users_groups
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :username,
				 uniqueness: true

	validates :password,
				 length: { minimum: 6}

	has_one :profile
	has_many :attendances
	has_many :events, through: :attendances
	has_many :groups, through: :users_groups
	has_and_belongs_to_many :users,
		:join_table => :follows,
		:foreign_key => "follower_id",
		:association_foreign_key => "followee_id"
end

app/models/users_group.rb
class UsersGroup < ActiveRecord::Base
	belongs_to :user
	belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
	def create
		@attendance = Attendance.new(event_id: params[:id], user_id: session[:user_id]) 

		if @attendance.save
			flash[:notice] = "You are now attending the event."
		else
			flash[:alert] = "Your attendance was not accepted."
		end
		
		redirect_to :back
	end
	def destroy
		@attendance = Attendance.where(event_id: params[:id], user_id: session[:user_id]).first
		if @attendance.destroy
			flash[:notice] = "You are no longer attending the event."
		else
			flash[:alert] = "Unattending was not successfully."
		end
		redirect_to :back
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	def index
		@events = Event.all.order(date: :asc)
		@attendances = User.find(session[:user_id]).attendances
	end
	
	def show
		@event = Event.find(params[:id])
		@attendances = User.find(session[:user_id]).attendances
	end

	def new
		@event = Event.new
	end

	def edit
		@event = Event.find(params[:id])
	end
	def update
		@event = Event.find(params[:id])
		if @event.update(event_params)
			flash[:notice] = "Your event was updated successfully."
		else
			flash[:alert] = "Event update failed"
		end

		redirect_to '/events'
	end
	def create
		@event = Event.new(event_params)
		@event.creator_id = session[:user_id]

		if @event.save
			flash[:notice] = "You have successfully added an event."
			redirect_to '/events'
		else
			if @event.errors.full_messages.any?
				flash[:alert] = []
				@event.errors.full_messages.each do |message|
					flash[:alert].push(message)  
				end
			end
			redirect_to :back
		end
	end

	def destroy
	end

	private
		def event_params
			params.require(:event).permit(:title, :description, :address_1, :address_2, :city, :state, :date, :time)
		end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	def index
		@groups = Group.all
	end
	def show
		@group = Group.find(params[:id])
	end
	def new
		@group = Group.new
	end
	def create
		@group = Group.new(group_params)

		if @group.save
			flash[:notice] = "You have successfully added a group."
			redirect_to '/groups'
		else
			flash[:alert] = "An error has occurred. Please try again."
			redirect_to :back
		end
	end

	private
		def group_params
			params.require(:group).permit(:title, :description)
		end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		if session[:user_id]
			redirect_to '/events'
		end
	end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	def show
		@offset = 0

		if params[:move]
			@offset += params[:move][4,params[:move].length].to_i
		end

		if params[:username]
			@profile = User.find_by(username: params[:username]).profile
		else
			@profile = Profile.find_by(user_id: session[:user_id])
		end

		showing_month = Time.now + @offset.month
		today = Time.now.strftime('%d').to_i
		days_in_this_month = Time.days_in_month(showing_month.strftime('%m').to_i,showing_month.strftime('%Y').to_i)
		@events = @profile.user.events.where("date between ? and ?", showing_month - (today).day, showing_month + (days_in_this_month-today).day)
	end

	def edit
		@profile = User.find(session[:user_id]).profile
	end

	def update
		@profile = Profile.find(session[:user_id])
		if @profile.update(profile_params)
			flash[:notice] = "Your profile was updated successfully."
		else
			flash[:alert] = "Profile update failed"
		end

		redirect_to '/profile'
	end
	private
		def profile_params
			params.require(:profile).permit(:first_name, :last_name, :gender, :email, :birthday, :work, :skills, :interests)
		end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
	def create
		if params[:login].include? '@'
			profile = Profile.find_by(email: params[:login])
			if profile
				user = profile.user
			end
		else
			user = User.find_by(username: params[:login])
		end

		if user
			if params[:password] == user.password
				session[:user_id] = user.id
				user.update(last_login: Time.now)
				flash[:notice] = "You have logged in successfully."
			else
				flash[:alert] = "Your login information is incorrect. Please try again."
			end	
		else
			flash[:alert] = "Your login information is incorrect. Please try again."
		end

		redirect_to root_path
	end
	
	def destroy
		session[:user_id] = nil
		flash[:notice] = "You have logged out successfully. Please come back soon."
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end
	def create
		if params[:email] == params[:email2] && params[:password] == params[:password2]
			@user = User.new(user_params)
			@user.last_login = Time.now
			if @user.save
				Profile.create(email: params[:email], user_id: @user.id)
				session[:user_id] = @user.id
				flash[:notice] = "You have successfully created an account."
			else
				flash[:alert] = "Your request for a new account failed. Please try again."
			end
		else
				flash[:alert] = "Your emails and/or passwords did not match. Please try again."
		end

		redirect_to root_path
	end
	private
		def user_params
			params.permit(:username, :password)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
	def full_name
		if @profile.first_name.nil? || @profile.first_name == ""
			@profile.user.username
		elsif @profile.last_name.nil? || @profile.last_name == ""
			@profile.first_name
		else
			@profile.first_name + " " + @profile.last_name
		end
	end
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<%= form_for @event do |f| %>
	<%= f.label :title %><br>
	<%= f.text_field :title %>
	<br><br>
	<%= f.label :description %><br>
	<%= f.text_area :description, cols: '50', rows: '20' %>
	<br><br>
	<%= f.label :address_1 %><br>
	<%= f.text_field :address_1 %>
	<br><br>
	<%= f.label :address_2 %><br>
	<%= f.text_field :address_2 %>
	<br><br>
	<%= f.label :city %> &nbsp;
	<%= f.text_field :city %>
	&nbsp; &nbsp;
	<%= f.label :state %> &nbsp;
	<%= f.text_field :state %>
	<br><br>
	<%= f.label :date %><br>
	<%= f.date_field :date %>
	<br><br>
	<%= f.label :time %><br>
	<%= f.time_field :time %>
	<br><br>
	<%= f.submit "Update Event" %>
<% end %>

app/views/events/index.html.erb
<h1>Events</h1>
<p><%= link_to "Add New Event", "events/new", method: "get" %></p>
<% if @events %>
	<% @events.each do |event| %>
		<% attending = false %>
		<% @attendances.each do |attendance| %>
			<% if attendance.event_id == event.id
				attending = true 
			end %>
		<% end %>
		<div class="event">
			<% title = event.title[0..19] + " ..." %>
			<%= link_to title, event_path(event) %>

			<% if attending %>
				<%= link_to "Unattend", "/events/#{event.id}/unattend" %>
			<% else %>
				<%= link_to "Attend", "/events/#{event.id}/attend" %>
			<% end %>

			<% if event.creator_id == session[:user_id] %>
				<%= link_to "Edit Event", edit_event_path(event), method: "get" %>
			<% end %>
			<br>
			Description:<br><%= event.description %>
			<br><br>
			Date: <%= event.date.strftime('%B-%d-%Y') %>
			Time: <%= event.time.strftime('%I:%M %P') %>
		</div>
	<% end %>
<% else %>
	There are no events to display.
<% end %>

<div class="clear"></div>

app/views/events/new.html.erb
<%= form_for @event do |f| %>
	<%= f.label :title %><br>
	<%= f.text_field :title %>
	<br><br>
	<%= f.label :description %><br>
	<%= f.text_area :description, cols: '50', rows: '20' %>
	<br><br>
	<%= f.label :address_1 %><br>
	<%= f.text_field :address_1 %>
	<br><br>
	<%= f.label :address_2 %><br>
	<%= f.text_field :address_2 %>
	<br><br>
	<%= f.label :city %> &nbsp;
	<%= f.text_field :city %>
	&nbsp; &nbsp;
	<%= f.label :state %> &nbsp;
	<%= f.text_field :state %>
	<br><br>
	<%= f.label :date %><br>
	<%= f.date_field :date %>
	<br><br>
	<%= f.label :time %><br>
	<%= f.time_field :time %>
	<br><br>
	<%= f.submit "Add Event" %>
<% end %>

app/views/events/show.html.erb
<p>
	Title: <%= @event.title %> 
	<br>
	Description:<br><%= @event.description %>
	<br><br>
	Date: <%= @event.date.strftime('%B-%d-%Y') %>
	<br>
	Time: <%= @event.time.strftime('%I:%M %P') %>
	<br>
	<div id="address">
	Address: <%= @event.address_1 %>
	<br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
	<% if @event.address_2 != "" %>
		<%= @event.address_2 %> 
		<br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
	<% end %>
	<%= @event.city %>, <%= @event.state %>
	</div>
</p>

<p>
	<h2>Attendees</h2>
	<% attendees = @event.users %>
	<% attendees.each do |attendee| %>
		<p><%= link_to attendee.username, "/profile/#{attendee.username}" %></p>
	<% end %>
</p>

<% attending = false 
	@attendances.each do |attendance|
		if attendance.event_id == @event.id
			attending = true %>
			<%= link_to "Unattend", "/events/#{@event.id}/unattend" %>
		<% end
	end %>

<% if attending == false %>
	<%= link_to "Attend", "/events/#{@event.id}/attend" %>
<% end %>

<% if @event.creator_id == session[:user_id] %>
	<%= link_to "Edit Event", edit_event_path(@event), method: "get" %>
<% end %>

app/views/groups/index.html.erb
<h1>Groups</h1>
<% if @groups %>
	<% @groups.each do |group| %>
		<p>
			<%= link_to group.title, group_path(group) %>
			<br>
			Description:<br><%= group.description %>
		</p>
	<% end %>
<% else %>
	There are no groups to display.
<% end %>

<%= link_to "Add New Group", "groups/new", method: "get" %>

app/views/groups/new.html.erb
<%= form_for @group do |f| %>
	<%= f.label :tile %><br>
	<%= f.text_field :title %>
	<br><br>
	<%= f.label :description %><br>
	<%= f.text_area :description, cols: '50', rows: '20' %>
	<br><br>
	<%= f.submit "Add Group" %>
<% end %>

app/views/groups/show.html.erb
<p>
	Title: <%= @group.title %>
	<br>
	Description:<br><%= @group.description %>
</p>

app/views/profiles/edit.html.erb
<%= form_for @profile, url: '/profile/update', method: "post" do |f| %>
	<%= f.label :first_name, "First Name " %>
	<%= f.text_field :first_name %>
	<br>
	<%= f.label :last_name, "Last Name " %>
	<%= f.text_field :last_name %>
	<br>
	<%= f.label :gender, "Gender " %>
	<%= f.select :gender, [['Male','Male'],['Female','female']], include_blank: true %>
	<br>
	<%= f.label :email, "email " %>
	<%= f.email_field :email %>
	<br>
	<%= f.label :birthday, "Birthday " %>
	<%= f.date_field :birthday %>
	<br>
	<%= f.label :work, "Work " %>
	<%= f.text_field :work %>
	<br>
	<%= f.label :skills, "Skills " %>
	<br>
	<%= f.text_area :skills %>
	<br>
	<%= f.label :interests, "Interests " %><br>
	<%= f.text_area :interests %>
	<br><br>
	<%= f.submit "Update Profile" %>
<% end %>

app/views/profiles/show.html.erb
<p>
	<%= link_to "Edit Profile", '/profile/edit', method: 'get' %>
</p>

<p>
	<h1><%= full_name %></h1>
	Gender: <%= @profile.gender if @profile.gender.present? %>
	<br><br>
	Email: <%= @profile.email if @profile.email.present? %>
	<br><br>
	Birthday: <%= @profile.birthday.strftime('%m-%d-%Y') if @profile.birthday.present? %>
	<br><br>
	Work: <%= @profile.work if @profile.work.present? %>
	<br><br>
	Skills: <%= @profile.skills if @profile.skills.present? %>
	<br><br>
	Interests: <%= @profile.interests if @profile.interests.present? %>
	<br><br>
</p>

<div id="calendar">
	<div id="cal_nav">
		<%= link_to 'Previous 5', "/profile/move/prev#{@offset-5}", method: 'get' %>
		<%= link_to 'Previous', "/profile/move/prev#{@offset-1}", method: 'get' %>

		<%= link_to 'Next', "/profile/move/next#{@offset+1}", method: 'get' %>
		<%= link_to 'Next 5', "/profile/move/next#{@offset+5}", method: 'get' %>
	</div>
	
	<% showing_month = Time.now + @offset.month %>

	<div id="monthly_header">
		<h1><%= showing_month.strftime('%B %Y') %></h1>
	</div>

	<% today = Time.now.strftime('%d').to_i %>

	<% days_in_this_month = Time.days_in_month(showing_month.strftime('%m').to_i,showing_month.strftime('%Y').to_i) %>

	<% first_day_in_this_month = (showing_month - (today-1).day).strftime('%w').to_i %>

	<% if today > days_in_this_month
		first_day_in_this_month += today - days_in_this_month 
	end %>

	<% day_of_week = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"] %>
	<% for i in 0...7 %>
		<div class="day_of_week">
			<h3><%= day_of_week[i] %></h3>
		</div>
	<% end %>

	<div class="clear"></div>

	<% day_count = 1 
		block_count = 0 %>

	<% if first_day_in_this_month < 7 %>
		<% for i in 1..first_day_in_this_month %>
			<div class="not_monthly_day">
			</div>
			<% block_count += 1 %>
		<% end %>
	<% end %>

	<% for i in first_day_in_this_month...7 %>
		<% block_count += 1 %>

		<% today_events = [] %>
		<% @events.each do |event| %>
			<% if event.date.strftime('%d').to_i == day_count %>
				<% today_events.push(event) %>
			<% end %>
		<% end %>

		<% if day_count == today && today <= days_in_this_month && showing_month.strftime('%m') == Time.now.strftime('%m') %>
			<div id="today">
				<h3><%= day_count %></h3>
				<% today_events.each do |event| %>
				<% title = event.title[0..15] + " ..." %>
					<p><%= link_to title, event_path(event) %></p>
				<% end %>
			</div>
		<% else %>
			<div class="monthly_day">
				<h3><%= day_count %></h3>
				<% today_events.each do |event| %>
					<% title = event.title[0..15] + " ..." %>
					<p><%= link_to title, event_path(event) %></p>
				<% end %>
			</div>
		<% end %>

		<% day_count+=1 %>
	<% end %>

	<div class="clear"></div>

	<% for i in 1..5 %>
		<% for i in 1..7 %>
			<% block_count += 1 %>

			<% today_events = [] %>
			<% @events.each do |event| %>
				<% if event.date.strftime('%d').to_i == day_count %>
					<% today_events.push(event) %>
				<% end %>
			<% end %>

			<% if day_count == today && today <= days_in_this_month && showing_month.strftime('%m') == Time.now.strftime('%m') %>
				<div id="today">
					<h3><%= day_count %></h3>
					<% today_events.each do |event| %>
					<% title = event.title[0..15] + " ..." %>
						<p><%= link_to title, event_path(event) %></p>
					<% end %>
				</div>
			<% elsif day_count <= days_in_this_month %>
				<div class="monthly_day">
					<h3><%= day_count %></h3>
					<% today_events.each do |event| %>
						<% title = event.title[0..15] + " ..." %>
						<p><%= link_to title, event_path(event) %></p>
					<% end %>
				</div>
			<% end %>

			<% day_count += 1 %>

			<% break if day_count > days_in_this_month %>
		<% end %>
		<div class="clear"></div>
	<% end %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>
<% @users.each do |user| %>
	<% if user.id != session[:user_id] %>
		<p>
			<%= link_to user.username, "/profile/#{user.username}" %>
		</p>
	<% end %>
<% end %>